### ISSUE TITLE
install not working with python 2.7

### ISSUE THREAD

**Issue by arugola** [hanzhichao2000/pysentiment#9]
I tried to install from both git and pip, but I'm getting the following:
```
import pysentiment as ps
  File "pysentiment/utils.py", line 9
    class BaseTokenizer(object, metaclass=abc.ABCMeta):
                                         ^
SyntaxError: invalid syntax
```
is this compatible with Python 2?

**Comment by zsayed09** [comment]
> I tried to install from both git and pip, but I'm getting the following:
> 
> ```
> import pysentiment as ps
>   File "pysentiment/utils.py", line 9
>     class BaseTokenizer(object, metaclass=abc.ABCMeta):
>                                          ^
> SyntaxError: invalid syntax
> ```
> 
> is this compatible with Python 2?

I am also facing the same issue.

**Comment by hanzhichao2000** [comment]
Python 2 is not supported any more.

**Comment by zsayed09** [comment]
> Python 2 is not supported any more.



> Python 2 is not supported any more.

Thanks for the update.
